import { z } from 'zod';
import { createRecordSchema,updateRecordSchema,deleteRecordSchema,updateSettingsSchema,localDateSchema,LedgerError } from '../contracts.ts';
import type { LedgerService, SettingsVersion, Settings, MutationReceipt, RecordQuery, LedgerRecord } from '../contracts.ts';
import { defaultSettings,taipeiToday,shiftDate,buildTodayPlan,summarizeIntake,foodSuggestions,progressionSuggestions,buildReview } from '../domain/index.ts';
import { LedgerRepository } from './repository.ts';
function canonical(value:unknown):string {if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(value!==null&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical((value as Record<string,unknown>)[k])}`).join(',')}}`;return JSON.stringify(value);}
async function operationHash(value:unknown):Promise<string>{const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(value)));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
function parse<S extends z.ZodTypeAny>(schema:S,value:unknown):z.output<S>{const parsed=schema.safeParse(value);if(!parsed.success)throw new LedgerError('invalid_values','資料格式或值不正確',422);return parsed.data;}
function identity(user:string):void {if(typeof user!=='string'||!user.trim())throw new LedgerError('unauthenticated','請先登入',401);}
function defaultVersion():SettingsVersion{return {revision:0,effective_from:null,updated_at:null,settings:defaultSettings()};}
function resolveSettings(history:SettingsVersion[],date?:string):SettingsVersion {return date===undefined?history.at(-1)??defaultVersion():[...history].filter(v=>v.effective_from!==null&&v.effective_from<=date).sort((a,b)=>a.effective_from!.localeCompare(b.effective_from!)||a.revision-b.revision).at(-1)??defaultVersion();}
const querySchema=z.object({from:localDateSchema.optional(),to:localDateSchema.optional(),kind:z.enum(['meal','workout','measurement','note']).optional(),limit:z.number().int().min(1).max(200).default(100),cursor:z.string().max(1000).optional()}).strict().refine(v=>!v.from||!v.to||v.from<=v.to);
function decodeCursor(cursor:string):{date:string;created:string;id:string}{try{const value=JSON.parse(atob(cursor));if(typeof value.date!=='string'||typeof value.created!=='string'||typeof value.id!=='string'||!localDateSchema.safeParse(value.date).success)throw new Error();return value;}catch{throw new LedgerError('invalid_query','分頁游標無效',400);}}
function sortRecords(records:LedgerRecord[]):LedgerRecord[]{return [...records].sort((a,b)=>b.local_date.localeCompare(a.local_date)||b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id));}
export function createLedgerService(db:D1Database):LedgerService {
 const repo=new LedgerRepository(db);
 const guard=<A extends unknown[],R>(fn:(user:string,...args:A)=>Promise<R>)=>async(user:string,...args:A):Promise<R>=>{identity(user);try{return await fn(user,...args);}catch(error){if(error instanceof LedgerError)throw error;throw new LedgerError('persistence_unavailable','帳本暫時無法保存或讀取，請保留輸入並稍後重試',503);}};
 async function getRecord(user:string,id:string){const record=await repo.record(user,id);if(!record)throw new LedgerError('not_found','找不到紀錄',404);return record;}
 async function mutation(user:string,request:string,hash:string,write:()=>Promise<void>):Promise<MutationReceipt>{const replay=await repo.replay(user,request,hash);if(replay)return replay as MutationReceipt;try{await write();}catch{const retry=await repo.replay(user,request,hash);if(retry)return retry as MutationReceipt;throw new LedgerError('persistence_unavailable','帳本暫時無法保存，請保留相同請求編號重試',503);}const saved=await repo.replay(user,request,hash);if(!saved)throw new LedgerError('revision_conflict','版本已改變，請重新讀取',409);return {...saved,replayed:false} as MutationReceipt;}
 const service:LedgerService={
  getSettings:guard(async(user,date)=>{if(date!==undefined)parse(localDateSchema,date);return resolveSettings(await repo.settings(user),date);}),
  updateSettings:guard(async(user,command)=>{
   const c=parse(updateSettingsSchema,command);const hash=await operationHash({operation:'settings',...c,request_id:undefined});const replay=await repo.replay(user,c.request_id,hash);if(replay)return replay as SettingsVersion;
   if(c.effective_from<taipeiToday())throw new LedgerError('invalid_effective_date','設定不可早於台北今天生效',422);
   const current=resolveSettings(await repo.settings(user));if(current.revision!==c.expected_revision)throw new LedgerError('revision_conflict','設定版本已改變，請重新讀取',409);
   const planKeys:(keyof Settings)[]=['start_date','target_date','energy_kcal','protein_g','carbs_target_g','fat_target_g','dumbbell_inventory_kg','dumbbell_increment_kg'];
   if(!c.confirm_plan_change&&planKeys.some(k=>canonical(c.settings[k])!==canonical(current.settings[k])))throw new LedgerError('plan_confirmation_required','變更目標或訓練設定需明確確認',422);
   const version:SettingsVersion={revision:current.revision+1,effective_from:c.effective_from,updated_at:new Date().toISOString(),settings:c.settings};
   try{await repo.updateSettings(user,c.request_id,hash,c.expected_revision,version);}catch{const retry=await repo.replay(user,c.request_id,hash);if(retry)return retry as SettingsVersion;throw new LedgerError('persistence_unavailable','暫時無法保存設定',503);}
   const saved=await repo.replay(user,c.request_id,hash);if(!saved)throw new LedgerError('revision_conflict','設定版本已改變',409);return saved as SettingsVersion;
  }),
  listRecords:guard(async(user,query:RecordQuery)=>{const parsed=querySchema.safeParse(query);if(!parsed.success)throw new LedgerError('invalid_query','查詢條件不正確',400);const q=parsed.data;const cursor=q.cursor?decodeCursor(q.cursor):null;const rows=sortRecords(await repo.records(user)).filter(r=>(!q.from||r.local_date>=q.from)&&(!q.to||r.local_date<=q.to)&&(!q.kind||r.kind===q.kind)&&(!cursor||r.local_date<cursor.date||(r.local_date===cursor.date&&(r.created_at<cursor.created||(r.created_at===cursor.created&&r.id<cursor.id)))));const page=rows.slice(0,q.limit);const last=page.at(-1);return {records:page,next_cursor:rows.length>q.limit&&last?btoa(JSON.stringify({date:last.local_date,created:last.created_at,id:last.id})):null};}),
  getRecord:guard(getRecord),
  createRecord:guard(async(user,command)=>{const c=parse(createRecordSchema,command);const hash=await operationHash({operation:'create',record:c.record});return mutation(user,c.request_id,hash,async()=>{const time=new Date().toISOString();const record={...c.record,id:crypto.randomUUID(),revision:1,created_at:time,updated_at:time};const receipt={record,id:record.id,revision:1,saved_at:time,replayed:false};await repo.create(user,c.request_id,hash,record,receipt);});}),
  updateRecord:guard(async(user,id,command)=>{const c=parse(updateRecordSchema,command);const hash=await operationHash({operation:'update',id,expected_revision:c.expected_revision,record:c.record});const replay=await repo.replay(user,c.request_id,hash);if(replay)return replay as MutationReceipt;const old=await getRecord(user,id);if(old.revision!==c.expected_revision)throw new LedgerError('revision_conflict','紀錄版本已改變，請重新讀取',409);const time=new Date().toISOString();const record={...c.record,id,revision:old.revision+1,created_at:old.created_at,updated_at:time};const receipt={record,id,revision:record.revision,saved_at:time,replayed:false};return mutation(user,c.request_id,hash,()=>repo.update(user,c.request_id,hash,c.expected_revision,record,receipt));}),
  deleteRecord:guard(async(user,id,command)=>{const c=parse(deleteRecordSchema,command);const hash=await operationHash({operation:'delete',id,expected_revision:c.expected_revision});const replay=await repo.replay(user,c.request_id,hash);if(replay)return replay as MutationReceipt;const old=await getRecord(user,id);if(old.revision!==c.expected_revision)throw new LedgerError('revision_conflict','紀錄版本已改變，請重新讀取',409);return mutation(user,c.request_id,hash,()=>repo.delete(user,id,c.request_id,hash,c.expected_revision,new Date().toISOString()));}),
  dashboard:guard(async(user,date)=>{parse(localDateSchema,date);const [all,history]=await Promise.all([repo.records(user),repo.settings(user)]);const settings=resolveSettings(history,date);const records=sortRecords(all.filter(r=>r.local_date===date));const intake=summarizeIntake(records,date);return {date,generated_at:new Date().toISOString(),settings,records,intake,plan:buildTodayPlan(date,settings.settings,all.filter(r=>r.local_date<=date)),suggestions:[...foodSuggestions(intake,settings.settings),...(settings.settings.target_date&&date>=shiftDate(settings.settings.target_date,-3)&&date<=settings.settings.target_date?[]:progressionSuggestions(all.filter(r=>r.local_date<=date),d=>resolveSettings(history,d).settings))],review:buildReview(all,date)};}),
  review:guard(async(user,date)=>{parse(localDateSchema,date);return buildReview(await repo.records(user),date);}),
  exportData:guard(async(user)=>{const [records,history,revisions]=await Promise.all([repo.records(user),repo.settings(user),repo.all<{payload:string}>('SELECT payload FROM ledger_revisions WHERE user_id=? ORDER BY record_id,revision',user)]);return {exported_at:new Date().toISOString(),schema_version:1,settings:resolveSettings(history),settings_history:history,records,revisions:revisions.map(r=>JSON.parse(r.payload)),scope:{cloud_records:true,local_photos:false,provider_chat:false}};})
 };
 return service;
}
