'use client';
import { Choice, CheckBox } from './controls';
import { useState } from 'react';
import { Plus, Save, Trash2, X } from 'lucide-react';
import { exerciseIds, loadModes, recordInputSchema, type ExerciseSet, type Workout } from '@/lib/contracts';
import { Field, NumberInput } from './settings';
import { Panel } from './shared';
import type { Write } from './writes';

export const exerciseNames = { goblet_squat: '高腳杯深蹲', dumbbell_rdl: '啞鈴羅馬尼亞硬舉', floor_press: '地板臥推', one_arm_row: '單手划船', dead_bug: '死蟲式', reverse_lunge: '反向弓步', glute_bridge: '臀橋', shoulder_press: '肩推', plank: '棒式' };
export const loadNames = { single_dumbbell_total: '單顆啞鈴總重量', per_dumbbell: '每手啞鈴重量', single_active_dumbbell: '單側使用的啞鈴重量', external_total: '外加總重量', bodyweight: '自體重量' };
const emptySet = (): ExerciseSet => ({ exercise_id: 'goblet_squat', set_type: 'work', load_mode: 'per_dumbbell', load_kg: null, reps: null, left_reps: null, right_reps: null, duration_seconds: null, rir: null, controlled_form: null, pain: null });
const nullableBoolean = (value: string) => value === '' ? null : value === 'true';

export function AddRecordForm({ kind, date, write, busy, onDone, onCancel }: { kind: 'measurement' | 'note' | 'workout'; date: string; write: Write; busy: boolean; onDone: () => void; onCancel: () => void }) {
  const [error, setError] = useState('');
  const [sets, setSets] = useState<ExerciseSet[]>([]);
  const [activity, setActivity] = useState<Workout['activity'] | ''>('');
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError('');
    const form = new FormData(event.currentTarget);
    const text = (key: string) => String(form.get(key) || '');
    const numeric = (key: string) => text(key) === '' ? null : Number(text(key));
    const common = { local_date: text('date'), date_confirmed: form.get('date_confirmed') === 'on' };
    let input: unknown;
    if (kind === 'measurement') input = { ...common, kind, data: { metric: text('metric'), value: Number(form.get('value')), source: 'measured', morning: nullableBoolean(text('morning')), notes: text('notes') } };
    else if (kind === 'note') input = { ...common, kind, data: { text: text('text'), linked_record_id: null, sleep_hours: numeric('sleep'), fatigue: text('fatigue'), soreness: text('soreness'), day_complete: form.get('day_complete') === 'on' } };
    else input = { ...common, kind, data: { activity, status: text('status'), title: text('title'), sets: activity === 'strength' ? sets : [], duration_seconds: numeric('duration') === null ? null : Math.round(Number(form.get('duration')) * 60 * 1000000) / 1000000, distance_km: numeric('distance'), machine_kcal: numeric('machine_kcal'), rpe: numeric('rpe'), recovery_ok: nullableBoolean(text('recovery')), safety_hold: form.get('safety_hold') === 'on', notes: text('notes') } };
    const parsed = recordInputSchema.safeParse(input);
    if (!parsed.success) { setError(`${parsed.error.issues[0]?.path.join(' / ')}：${parsed.error.issues[0]?.message}`); return; }
    if (await write('/records', 'POST', { record: parsed.data }, common.date_confirmed ? '紀錄' : '日期待確認草稿')) onDone();
  }
  function updateSet(index: number, patch: Partial<ExerciseSet>) { setSets(previous => previous.map((item, i) => i === index ? { ...item, ...patch } : item)); }
  return <Panel title={{ measurement: '補記實際量測', note: '補充一般備註', workout: '手動記錄訓練' }[kind]} eyebrow="ADD WHAT ACTUALLY HAPPENED" action={<button className="icon-button" aria-label="關閉新增表單" onClick={onCancel}><X size={18} /></button>}><form onSubmit={submit}><Field label="實際日期（台北時間）"><input name="date" type="date" defaultValue={date} required /></Field><label className="checkbox-field"><CheckBox name="date_confirmed"  />我確認這是實際發生日期</label><p className="muted small-text form-intro">未確認日期可保存為草稿，暫不計入當日小計與趨勢。</p>
    {kind === 'measurement' && <div className="form-grid"><Field label="量測項目"><Choice name="metric"><option value="weight_kg">體重（kg）</option><option value="waist_cm">腰圍（cm）</option></Choice></Field><Field label="實際數值"><NumberInput name="value" min={.000001} max={500} required /></Field><Field label="晨起量測條件"><Choice name="morning" defaultValue=""><option value="">未知／未確認</option><option value="true">是，已確認晨起量測</option><option value="false">不是晨起量測</option></Choice></Field><Field label="量測補充"><textarea name="notes" maxLength={500} /></Field></div>}
    {kind === 'note' && <><Field label="備註內容"><textarea name="text" maxLength={2000} required placeholder="寫下睡眠、恢復或一般觀察。" /></Field><div className="form-grid"><Field label="自述睡眠（小時）"><NumberInput name="sleep" min={0} max={24} /></Field><Field label="疲勞狀態"><Choice name="fatigue" defaultValue="unknown"><option value="unknown">未確認</option><option value="good">精神良好</option><option value="normal">一般</option><option value="poor">疲勞明顯</option></Choice></Field><Field label="痠痛"><Choice name="soreness" defaultValue="unknown"><option value="unknown">未確認</option><option value="none">沒有</option><option value="mild">輕微</option><option value="affects_movement">影響動作</option></Choice></Field></div><label className="checkbox-field"><CheckBox name="day_complete"  />我已完整回報這一天的飲食</label><p className="muted small-text">一般備註不會新增攝取量或已完成訓練。</p></>}
    {kind === 'workout' && <><div className="form-grid"><Field label="訓練類型"><Choice value={activity} required onChange={e => setActivity(e.target.value as Workout['activity'])}><option value="">請選擇</option><option value="strength">肌力</option><option value="run">跑步</option><option value="dance">舞蹈</option><option value="recovery">恢復／休息</option></Choice></Field><Field label="實際狀態"><Choice name="status" required defaultValue=""><option value="">請確認狀態</option><option value="completed">已完成</option><option value="partial">部分完成</option><option value="planned">尚未完成，僅計畫</option><option value="rest">休息</option></Choice></Field><Field label="訓練名稱"><input name="title" required maxLength={150} placeholder="寫下實際做的訓練" /></Field><Field label="含暖身、休息、緩和的總時間（分鐘）"><NumberInput name="duration" min={.000001} max={1440} /></Field><Field label="距離（km）"><NumberInput name="distance" min={.01} max={500} /></Field><Field label="機台顯示熱量（kcal，設備估計）"><NumberInput name="machine_kcal" min={0} max={10000} /></Field><Field label="RPE：這次整體有多費力（0–10）"><NumberInput name="rpe" min={0} max={10} /></Field><Field label="恢復狀態"><Choice name="recovery" defaultValue=""><option value="">未確認</option><option value="true">已確認恢復足夠</option><option value="false">恢復不足</option></Choice></Field></div><label className="checkbox-field"><CheckBox name="safety_hold"  />暫停進階</label>
      {activity === 'strength' && <div className="sets-editor"><div className="editor-heading"><h3>實際做過的每一組</h3><button className="button secondary" type="button" onClick={() => setSets(previous => [...previous, emptySet()])} disabled={sets.length >= 80}><Plus size={16} />新增一組</button></div><p className="muted small-text">重量不從計畫填入。單側動作分別記左右；暖身組不計為工作組。未知保留空白。</p>{sets.map((set, i) => <fieldset className="item-editor" key={i}><legend>第 {i + 1} 筆</legend><div className="editor-heading"><strong className="small-text">實際組次</strong><button type="button" className="icon-button delete" aria-label={`移除第 ${i + 1} 組`} onClick={() => setSets(previous => previous.filter((_, index) => index !== i))}><Trash2 size={16} /></button></div><div className="form-grid"><Field label="動作"><Choice value={set.exercise_id} onChange={e => updateSet(i, { exercise_id: e.target.value as ExerciseSet['exercise_id'] })}>{exerciseIds.map(id => <option key={id} value={id}>{exerciseNames[id]}</option>)}</Choice></Field><Field label="組別"><Choice value={set.set_type} onChange={e => updateSet(i, { set_type: e.target.value as ExerciseSet['set_type'] })}><option value="work">工作組</option><option value="warmup">暖身組</option></Choice></Field><Field label="重量計法"><Choice value={set.load_mode} onChange={e => updateSet(i, { load_mode: e.target.value as ExerciseSet['load_mode'] })}>{loadModes.map(mode => <option key={mode} value={mode}>{loadNames[mode]}</option>)}</Choice></Field>{([{ key: 'load_kg', label: '外加重量（kg）', max: 300 }, { key: 'reps', label: '雙側／一般次數', max: 200 }, { key: 'left_reps', label: '左側次數', max: 200 }, { key: 'right_reps', label: '右側次數', max: 200 }, { key: 'duration_seconds', label: '持續秒數', max: 3600 }, { key: 'rir', label: 'RIR：預估還能再做幾下（0–10）', max: 10 }] as const).map(field => <Field label={field.label} key={field.key}><input type="number" min="0" max={field.max} step={field.key.endsWith('reps') ? '1' : 'any'} value={set[field.key] ?? ''} placeholder="未知" onChange={e => updateSet(i, { [field.key]: e.target.value === '' ? null : Number(e.target.value) })} /></Field>)}<Field label="動作品質"><Choice value={set.controlled_form === null ? '' : String(set.controlled_form)} onChange={e => updateSet(i, { controlled_form: nullableBoolean(e.target.value) })}><option value="">未確認</option><option value="true">已確認控制穩定</option><option value="false">控制不穩定</option></Choice></Field><Field label="是否疼痛"><Choice value={set.pain === null ? '' : String(set.pain)} onChange={e => updateSet(i, { pain: nullableBoolean(e.target.value) })}><option value="">未確認</option><option value="false">已確認沒有疼痛</option><option value="true">有疼痛</option></Choice></Field></div></fieldset>)}</div>}
      <Field label="訓練補充（自述）"><textarea name="notes" maxLength={1000} /></Field></>}
    {error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions"><button type="submit" className="button primary" disabled={busy}><Save size={17} />{busy ? '保存中…' : '保存紀錄'}</button><button type="button" className="button secondary" onClick={onCancel} disabled={busy}>取消</button></div>
  </form></Panel>;
}
