'use client';
import { useState } from 'react';
import { Line, LineChart, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import type { Review, WeightPoint } from '@/lib/contracts';
import { Panel, Suggestions } from './shared';

export function Trends({ review }: { review: Review }) {
  const [metric, setMetric] = useState<'weight' | 'waist'>('weight');
  const points = metric === 'weight' ? review.weight_points : review.waist_points;
  return <><Panel title="量測的變化" eyebrow="YOUR REAL MEASUREMENTS" action={<div className="segmented"><button className={metric === 'weight' ? 'selected' : ''} onClick={() => setMetric('weight')}>體重</button><button className={metric === 'waist' ? 'selected' : ''} onClick={() => setMetric('waist')}>腰圍</button></div>}><p className="muted chart-description">{metric === 'weight' ? '僅納入已確認日期的晨重；每天多筆採最後一筆。' : '已確認日期的腰圍量測。'}沒有量測的日期不補數字。</p><MeasurementChart points={points} unit={metric === 'weight' ? 'kg' : 'cm'} /><details className="data-table"><summary>查看圖表原始數值（{points.length} 筆）</summary>{points.length ? <table><thead><tr><th>日期</th><th>實際量測</th></tr></thead><tbody>{points.map((point, i) => <tr key={`${point.date}-${i}`}><td>{point.date}</td><td>{point.value} {metric === 'weight' ? 'kg' : 'cm'}</td></tr>)}</tbody></table> : <p className="muted">尚無符合條件的量測。</p>}</details></Panel>
    <div className="window-grid">{[{ title: '本週 7 日晨重', window: review.current }, { title: '前週 7 日晨重', window: review.previous }].map(item => <Panel key={item.title} title={item.title}><p className="muted small-text">{item.window.from} — {item.window.to}</p><p className="window-average">{item.window.average_kg === null ? '資料不足' : item.window.average_kg.toFixed(2)}{item.window.average_kg !== null && <small> kg</small>}</p><p className="small-text muted">有效晨重 {item.window.sample_count} 日／7 日 · 每週至少 3 日才計算平均</p></Panel>)}</div>
    <Panel title="兩週回顧" eyebrow="EVIDENCE BEFORE ADJUSTMENT" action={<span className="tag">{{ insufficient_data: '資料不足', maintain: '維持觀察', review: '待你回顧' }[review.status]}</span>}><div className="review-stats"><div><strong>{review.reported_days}</strong><span>有餐點回報的日數</span></div><div><strong>{review.complete_days}</strong><span>標記完整的日數</span></div><div><strong>{review.training_sessions}</strong><span>訓練紀錄</span></div><div><strong>{review.recovery_flags}</strong><span>恢復提醒</span></div></div><p className="muted small-text">週平均變化：{review.weight_change_kg === null ? '資料不足，尚無可比較值' : `${review.weight_change_kg > 0 ? '+' : ''}${review.weight_change_kg.toFixed(2)} kg`}。少量數據或單日上升不會自動更改飲食目標。</p><ul className="review-messages">{review.messages.map((message, i) => <li key={i}>{message}</li>)}</ul><Suggestions suggestions={review.suggestions} /></Panel>
  </>;
}
function MeasurementChart({ points, unit }: { points: WeightPoint[]; unit: string }) {
  if (!points.length) return <div className="empty-state"><strong>先從一筆量測開始</strong><p>到「紀錄」補記體重或腰圍，有足夠資料後再觀察變化。</p></div>;
  return <div className="chart" role="img" aria-label={`${unit === 'kg' ? '體重' : '腰圍'}趨勢圖，共 ${points.length} 筆量測；完整數值可展開下方表格`}><ResponsiveContainer width="100%" height="100%"><LineChart data={points.map(point => ({ ...point, timestamp: new Date(`${point.date}T00:00:00Z`).valueOf() }))} margin={{ top: 20, right: 15, left: 0, bottom: 10 }}><CartesianGrid stroke="#edf1f8" vertical={false} /><XAxis dataKey="timestamp" type="number" domain={['dataMin', 'dataMax']} tickFormatter={value => new Date(Number(value)).toISOString().slice(5, 10)} tick={{ fill: '#8291a8', fontSize: 12 }} tickLine={false} axisLine={false} minTickGap={32} /><YAxis domain={['auto', 'auto']} tick={{ fill: '#8291a8', fontSize: 12 }} tickLine={false} axisLine={false} width={48} unit={` ${unit}`} /><Tooltip labelFormatter={label => new Date(Number(label)).toISOString().slice(0, 10)} formatter={value => [`${value} ${unit}`, '實際量測']} contentStyle={{ borderRadius: 10, borderColor: '#e3e8f0' }} /><Line type="linear" dataKey="value" stroke="#315ee7" strokeWidth={2.5} dot={{ fill: '#fff', stroke: '#315ee7', r: 4 }} activeDot={{ r: 6 }} isAnimationActive={false} /></LineChart></ResponsiveContainer></div>;
}
